declare var _default: {
    status: string[];
    getSessions: string[];
    getSession: string[];
    deleteSession: string[];
    setTimeouts: (string | string[])[];
    setAsyncScriptTimeout: (string | string[])[];
    setImplicitWaitTimeout: (string | string[])[];
    getWindowHandle: string[];
    getWindowHandles: string[];
    switchToWindow: (string | string[])[];
    closeWindow: string[];
    setWindowSize: (string | string[])[];
    getWindowSize: string[];
    setWindowPosition: (string | string[])[];
    getWindowPosition: string[];
    maximizeWindow: string[];
    getCurrentURL: string[];
    go: (string | string[])[];
    goForward: string[];
    goBack: string[];
    refresh: string[];
    executeScript: (string | string[])[];
    executeAsyncScript: (string | string[])[];
    screenshot: string[];
    switchToFrame: (string | string[])[];
    switchToParentFrame: string[];
    getAllCookies: string[];
    setCookie: (string | string[])[];
    deleteAllCookies: string[];
    deleteCookie: string[];
    getSource: string[];
    getTitle: string[];
    findElement: (string | string[])[];
    findElements: (string | string[])[];
    getActiveElement: string[];
    findChildElement: (string | string[])[];
    findChildElements: (string | string[])[];
    keys: (string | string[])[];
    click: string[];
    clear: string[];
    submit: string[];
    getElementText: string[];
    keysElement: (string | string[])[];
    getElementTagName: string[];
    isElementSelected: string[];
    isElementEnabled: string[];
    getElementAttribute: string[];
    isElementEqual: string[];
    isElementDysplayed: string[];
    getElementLocation: string[];
    getElementLocationInView: string[];
    getElementSize: string[];
    getElementCssProperty: string[];
    getOrientation: string[];
    setOrientation: (string | string[])[];
    getAlertText: string[];
    setAlertText: (string | string[])[];
    acceptAlert: string[];
    dismissAlert: string[];
    mouseMoveTo: (string | string[])[];
    mouseClick: (string | string[])[];
    mouseDoubleClick: string[];
    mouseDown: (string | string[])[];
    mouseUp: (string | string[])[];
    touchClick: (string | string[])[];
    touchDown: (string | string[])[];
    touchUp: (string | string[])[];
    touchMove: (string | string[])[];
    touchScroll: (string | string[])[];
    touchDoubleClick: (string | string[])[];
    touchLongClick: (string | string[])[];
    touchFlick: (string | string[])[];
    getGeoLocation: string[];
    setGeoLocation: (string | string[])[];
    setLocalStorage: (string | string[])[];
    getLocalStorageKeys: string[];
    clearLocalStorage: string[];
    getLocalStorageValue: string[];
    deleteLocalStorageValue: string[];
    getLocalStorageSize: string[];
    getSessionStorageKeys: string[];
    setSessionStorage: (string | string[])[];
    deleteSessionStorage: string[];
    getSessionStorageValue: string[];
    deleteSessionStorageValue: string[];
    getSessionStorageSize: string[];
};
export default _default;
