/// <reference types="node" />
export * from '../webdriver';
import { Webdriver, Capabilities, Timeouts, LocatorStrategy } from '../webdriver';
import { CommandHistoryObject } from './command-history';
export declare abstract class Base {
    options: BrowserOptions;
    webdriver: Webdriver;
    capabilities: Capabilities;
    sessionId: string;
    started: boolean;
    protected _: this;
    protected static _no_command_history_list: string[];
    protected static _no_proxy_list: string[];
    protected static DEFAULT_WAIT_TIMEOUT: number;
    protected static DEFAULT_WAIT_INTERVAL: number;
    protected static MAX_COMMAND_HISTORY_ITEMS: number;
    static readonly KEY: {
        null: string;
        cancel: string;
        help: string;
        back_space: string;
        backspace: string;
        tab: string;
        clear: string;
        return: string;
        enter: string;
        shift: string;
        control: string;
        ctrl: string;
        alt: string;
        pause: string;
        escape: string;
        space: string;
        pageup: string;
        page_up: string;
        pagedown: string;
        page_down: string;
        end: string;
        home: string;
        left_arrow: string;
        arrow_left: string;
        leftarrow: string;
        arrowleft: string;
        up_arrow: string;
        arrow_up: string;
        uparrow: string;
        arrowup: string;
        right_arrow: string;
        arrow_right: string;
        rightarrow: string;
        arrowright: string;
        down_arrow: string;
        arrow_down: string;
        downarrow: string;
        arrowdown: string;
        insert: string;
        delete: string;
        semicolon: string;
        equals: string;
        numpad_0: string;
        numpad_1: string;
        numpad_2: string;
        numpad_3: string;
        numpad_4: string;
        numpad_5: string;
        numpad_6: string;
        numpad_7: string;
        numpad_8: string;
        numpad_9: string;
        numpad0: string;
        numpad1: string;
        numpad2: string;
        numpad3: string;
        numpad4: string;
        numpad5: string;
        numpad6: string;
        numpad7: string;
        numpad8: string;
        numpad9: string;
        multiply: string;
        add: string;
        separator: string;
        subtract: string;
        decimal: string;
        divide: string;
        f1: string;
        f2: string;
        f3: string;
        f4: string;
        f5: string;
        f6: string;
        f7: string;
        f8: string;
        f9: string;
        f10: string;
        f11: string;
        f12: string;
        command: string;
        meta: string;
    };
    protected _numCommand: number;
    commandHistory: CommandHistoryObject[];
    logStream: NodeJS.WritableStream;
}
export interface PauseSettings {
    click?: number;
    navigate?: number;
    mouse?: number;
    keys?: number;
    submit?: number;
    upload?: number;
}
export interface WebElement {
    ELEMENT: string;
    using?: LocatorStrategy | [LocatorStrategy, LocatorStrategy];
    value?: string | [string, string];
    index?: number;
}
export declare type Selector = string | WebElement;
export interface BrowserOptions extends BrowserStartOptions {
    remote: string;
    log?: string | boolean;
    waitTimeout?: number;
    waitInterval?: number;
    pause?: PauseSettings;
    noCommandHistory?: boolean;
}
export interface BrowserStartOptions {
    proxy?: string;
    url?: string;
    maximaze?: boolean;
    windowSize?: number[];
    windowPosition?: number[];
    window?: number[];
    timeouts?: Timeouts;
    desiredCapabilities?: Capabilities;
}
